# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'heater.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(934, 812)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 40, 402, 654))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.VoltageControlPortLabel = QtWidgets.QLabel(self.layoutWidget)
        self.VoltageControlPortLabel.setObjectName("VoltageControlPortLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.VoltageControlPortLabel)
        self.VoltageControlPortSelection = QtWidgets.QComboBox(self.layoutWidget)
        self.VoltageControlPortSelection.setEditable(False)
        self.VoltageControlPortSelection.setObjectName("VoltageControlPortSelection")
        self.VoltageControlPortSelection.addItem("")
        self.VoltageControlPortSelection.addItem("")
        self.VoltageControlPortSelection.addItem("")
        self.VoltageControlPortSelection.addItem("")
        self.VoltageControlPortSelection.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.VoltageControlPortSelection)
        self.SetCOMPortsButton = QtWidgets.QPushButton(self.layoutWidget)
        self.SetCOMPortsButton.setObjectName("SetCOMPortsButton")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.SetCOMPortsButton)
        self.HeatingModeLabel = QtWidgets.QLabel(self.layoutWidget)
        self.HeatingModeLabel.setObjectName("HeatingModeLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.HeatingModeLabel)
        self.HeatingModeSelection = QtWidgets.QComboBox(self.layoutWidget)
        self.HeatingModeSelection.setObjectName("HeatingModeSelection")
        self.HeatingModeSelection.addItem("")
        self.HeatingModeSelection.addItem("")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.HeatingModeSelection)
        self.StartStopHeatingButton = QtWidgets.QPushButton(self.layoutWidget)
        self.StartStopHeatingButton.setObjectName("StartStopHeatingButton")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.StartStopHeatingButton)
        self.GetTempButton = QtWidgets.QPushButton(self.layoutWidget)
        self.GetTempButton.setObjectName("GetTempButton")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.GetTempButton)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget)
        self.label_14.setObjectName("label_14")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.SpanningRole, self.label_14)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.pushButton)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.PyrometerTemp = QtWidgets.QLineEdit(self.layoutWidget)
        self.PyrometerTemp.setObjectName("PyrometerTemp")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.PyrometerTemp)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.label_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 934, 38))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.VoltageControlPortSelection.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.VoltageControlPortLabel.setText(_translate("MainWindow", "1867B Voltage Control"))
        self.VoltageControlPortSelection.setItemText(0, _translate("MainWindow", "COM1"))
        self.VoltageControlPortSelection.setItemText(1, _translate("MainWindow", "COM2"))
        self.VoltageControlPortSelection.setItemText(2, _translate("MainWindow", "COM3"))
        self.VoltageControlPortSelection.setItemText(3, _translate("MainWindow", "COM4"))
        self.VoltageControlPortSelection.setItemText(4, _translate("MainWindow", "COM5"))
        self.SetCOMPortsButton.setText(_translate("MainWindow", "Set COM Port"))
        self.HeatingModeLabel.setText(_translate("MainWindow", "Heating Target:"))
        self.HeatingModeSelection.setItemText(0, _translate("MainWindow", "100C"))
        self.HeatingModeSelection.setItemText(1, _translate("MainWindow", "140C"))
        self.StartStopHeatingButton.setText(_translate("MainWindow", "Start/Stop Heating"))
        self.GetTempButton.setText(_translate("MainWindow", "Start/Stop temperature acquisition"))
        self.label_14.setText(_translate("MainWindow", "Initial Ramp Voltage (V) HAS TO BE INT"))
        self.pushButton.setText(_translate("MainWindow", "Set Initial Ramp Voltage"))
        self.label_12.setText(_translate("MainWindow", "Substrate Temperature (C)"))
        self.label_4.setText(_translate("MainWindow", "Status:"))

